spring:
  profiles:
    active: local
  application:
    name: capstoneDrazen
  datasource:
    url: jdbc:postgresql://${profile.datasource.host}:${profile.datasource.port}/capstoneDrazenDB
    username: ${profile.datasource.user}
    password: ${profile.datasource.pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  security:
    user:
      name: admin
      password: minda

server:
  servlet:
    context-path: "/api/${spring.application.name}"

