
spring:
  application:
    name: capstoneDrazen
  datasource:
    url: jdbc:postgresql://localhost:5432/capstoneDrazenDB
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: "/api/${spring.application.name}"